#!/usr/bin/env python3
"""Extract the Move's 5x7 OLED glyphs from the device font atlas into a TS module.

The real device renders text from a bitmap atlas (schwung loads
`/data/UserData/schwung/host/font.png` via js_display.c). The emulator's "Exact"
mode reproduces those literal device pixels, so it must use the SAME glyphs — not
a browser system font. This reads the built atlas + its charlist and emits
`src/host/device-font.ts` (char -> 7 row bitstrings, width 5).

Run from the overture repo root (needs Pillow + a built schwung):
    python3 web/scripts/extract-device-font.py
Regenerate only when the device font changes.
"""
import json
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]  # overture/
ATLAS = ROOT / "schwung/build/host/font.png"
CHARLIST = ROOT / "schwung/build/host/font.png.dat"
OUT = ROOT / "web/src/host/device-font.ts"


def main() -> int:
    if not ATLAS.exists():
        print(f"ERROR: {ATLAS} not found — build schwung first.", file=sys.stderr)
        return 1
    im = Image.open(ATLAS).convert("RGBA")
    w, h = im.size
    px = im.load()
    chars = CHARLIST.read_text().rstrip("\n")
    cell = w // len(chars)  # fixed-width cells (5px); atlas width == cells * chars
    if cell * len(chars) != w:
        print(f"ERROR: atlas width {w} not divisible by {len(chars)} chars", file=sys.stderr)
        return 1

    font: dict[str, list[str]] = {}
    for i, c in enumerate(chars):
        sx = i * cell
        font[c] = ["".join("1" if px[sx + dx, y][3] > 0 else "0" for dx in range(cell)) for y in range(h)]

    body = json.dumps(font, ensure_ascii=False, indent=0).replace("\n", "")
    OUT.write_text(
        "// The Move OLED's 5x7 device font, extracted from the schwung atlas\n"
        "// (schwung/build/host/font.png). Generated by web/scripts/extract-device-font.py —\n"
        "// do not edit by hand. char -> 7 row bitstrings, each `cell` (5) wide; '1' = lit.\n"
        f"// Atlas: {w}x{h}, {len(chars)} glyphs, cell {cell}x{h}.\n"
        f"export const DEVICE_FONT: Record<string, string[]> = {body};\n"
    )
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(font)} glyphs, cell {cell}x{h}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
