import { writeFileSync } from "node:fs";
import * as content from "./content";
import * as md from "./md";
import { GUIDE_PATH } from "./paths";
import type { Scene, Section } from "./types";

// Emit the canonical markdown guide as a list of blocks (see md.ts): framing
// intro + cross-links, a table of contents, a controls cheat-sheet, the captured
// walkthrough sections, then a glossary.
export function writeGuide(sections: Section[], scenes: Scene[]): void {
  const linkLine = content.links.map((l) => `${md.link(l.label, l.href)} — ${l.note}`).join(" · ");

  const blocks: string[] = [
    md.h1("Overture Beginner Guide"),
    md.comment(
      "Generated by `pnpm -C web manual:generate`. Edit web/tests/manual/scenarios.ts (walkthrough) and content.ts (intro, cheat-sheet, glossary)."
    ),
    ...content.intro.map(md.p),
    md.p(`**Where to go deeper:** ${linkLine}`),
  ];

  // Table of contents — one entry per scene plus the reference sections. Slugs
  // match GitHub's heading anchors so the links resolve in any markdown viewer.
  const toc = [
    md.link("Controls cheat-sheet", "#controls-cheat-sheet"),
    ...scenes.map((s) => md.link(s.title, `#${s.slug}`)),
    md.link("Glossary", "#glossary"),
  ];
  blocks.push(md.h2("Contents"), md.ul(toc));

  // Cheat-sheet up front so a reader can scan the controls before the walkthrough.
  blocks.push(
    md.h2("Controls cheat-sheet"),
    md.table(
      ["Control", "Gesture", "What it does"],
      content.cheatSheet.map((r) => [r.control, r.gesture, r.does])
    )
  );

  // The captured walkthrough.
  for (const section of sections) {
    blocks.push(md.h2(section.title));
    for (const para of section.body) blocks.push(md.p(para));
    for (const shot of section.shots) {
      blocks.push(md.h3(shot.title), md.img(shot.title, `assets/${shot.file}`), md.p(shot.caption));
    }
  }

  // Glossary, then a repeated cross-link footer.
  blocks.push(
    md.h2("Glossary"),
    md.table(
      ["Term", "Meaning"],
      content.glossary.map((g) => [g.term, g.def])
    ),
    "---",
    md.p(linkLine)
  );

  writeFileSync(GUIDE_PATH, md.doc(blocks), "utf8");
}
