import { writeFileSync } from "node:fs";
import * as md from "./md";
import type { GuideConfig, Scene, Section } from "./types";

// Emit a markdown guide as a list of blocks (see md.ts): framing intro +
// cross-links, a table of contents, a controls cheat-sheet, the captured
// walkthrough sections, then a glossary. The same emitter serves the beginner
// guide and the full reference — everything that differs comes from `cfg`.
export function writeGuide(sections: Section[], scenes: Scene[], cfg: GuideConfig): void {
  const linkLine = cfg.links.map((l) => `${md.link(l.label, l.href)} — ${l.note}`).join(" · ");

  const blocks: string[] = [
    md.h1(cfg.title),
    md.comment(`Generated by \`${cfg.generateCmd}\`. ${cfg.editHint}`),
    ...cfg.intro.map(md.p),
  ];
  if (linkLine) blocks.push(md.p(`**Where to go deeper:** ${linkLine}`));

  // Table of contents — one entry per scene plus the reference sections. Slugs
  // match GitHub's heading anchors so the links resolve in any markdown viewer.
  const toc = [
    md.link("Controls cheat-sheet", "#controls-cheat-sheet"),
    ...scenes.map((s) => md.link(s.title, `#${s.slug}`)),
    md.link("Glossary", "#glossary"),
  ];
  blocks.push(md.h2("Contents"), md.ul(toc));

  // Cheat-sheet up front so a reader can scan the controls before the walkthrough.
  blocks.push(
    md.h2("Controls cheat-sheet"),
    md.table(
      ["Control", "Gesture", "What it does"],
      cfg.cheatSheet.map((r) => [r.control, r.gesture, r.does])
    )
  );

  // The captured walkthrough.
  for (const section of sections) {
    blocks.push(md.h2(section.title));
    for (const para of section.body) blocks.push(md.p(para));
    for (const shot of section.shots) {
      blocks.push(md.h3(shot.title), md.img(shot.title, `assets/${shot.file}`), md.p(shot.caption));
    }
  }

  // Glossary, then a repeated cross-link footer.
  blocks.push(
    md.h2("Glossary"),
    md.table(
      ["Term", "Meaning"],
      cfg.glossary.map((g) => [g.term, g.def])
    )
  );
  if (linkLine) blocks.push("---", md.p(linkLine));

  writeFileSync(cfg.mdPath, md.doc(blocks), "utf8");
}
