import { writeFileSync } from "node:fs";
import rehypeSlug from "rehype-slug";
import rehypeStringify from "rehype-stringify";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { unified } from "unified";
import type { GuideConfig, Scene } from "./types";

// Styled standalone HTML build of the guide. Markdown is the canonical document;
// this writer only renders that markdown and wraps it in the Overture page shell.

const esc = (s: string): string =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const STYLE = `
  :root {
    --bg: #101214; --panel: #202327; --panel-2: #2a2e34; --line: #434952;
    --text: #f1f4f8; --muted: #b4bdc8; --accent: #19f0a8; --badge: #23d7ff;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--text);
    font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
  }
  code { font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 0.9em;
    background: var(--panel-2); border: 1px solid var(--line); border-radius: 4px; padding: 0.05em 0.35em; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  .wrap { max-width: 1180px; margin: 0 auto; padding: 2.5rem 1.5rem 4rem;
    display: grid; grid-template-columns: 240px 1fr; gap: 2.5rem; align-items: start; }
  header.brand { grid-column: 1 / -1; display: flex; align-items: baseline; gap: 0.6rem;
    border-bottom: 1px solid var(--line); padding-bottom: 1rem; }
  header.brand .name { font: 700 0.95rem/1 ui-monospace, monospace; letter-spacing: 0.28em; color: var(--accent); }
  header.brand .sub { font: 0.95rem/1 ui-monospace, monospace; letter-spacing: 0.2em; color: var(--muted); }
  nav { position: sticky; top: 1.5rem; font-size: 0.9rem; }
  nav .label { text-transform: uppercase; letter-spacing: 0.18em; font-size: 0.7rem; color: var(--muted); margin-bottom: 0.6rem; }
  nav ol { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.35rem; }
  nav a { color: var(--muted); display: block; padding: 0.2rem 0; border-left: 2px solid transparent; padding-left: 0.7rem; }
  nav a:hover { color: var(--text); border-left-color: var(--accent); text-decoration: none; }
  main { min-width: 0; }
  h1 { font-size: 2rem; line-height: 1.15; margin: 0 0 1rem; }
  #contents, #contents + ul { display: none; }
  h2 { font-size: 1.5rem; margin: 2.4rem 0 0.8rem; padding-top: 0.6rem; border-top: 1px solid var(--line); }
  h2:first-of-type { border-top: none; }
  h3 { font-size: 1.05rem; color: var(--muted); margin: 1.6rem 0 0.6rem; }
  p { margin: 0.6rem 0; }
  hr { border: 0; border-top: 1px solid var(--line); margin: 2.5rem 0 1.2rem; }
  main > ul { margin: 0.6rem 0 1.2rem; padding-left: 1.2rem; }
  main > ul li { margin: 0.25rem 0; }
  p:has(> img:only-child) { margin: 1rem 0 0.4rem; }
  img { max-width: 100%; height: auto; display: block; border: 1px solid var(--line); border-radius: 8px; background: #000; }
  h3 + p:has(> img:only-child) + p { font-size: 0.88rem; color: var(--muted); margin-top: 0.5rem; }
  h3 + p:has(> img:only-child) + p strong { color: var(--text); }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.92rem; }
  th, td { text-align: left; padding: 0.5rem 0.8rem; border: 1px solid var(--line); vertical-align: top; }
  th { background: var(--panel-2); color: var(--text); font-weight: 600; }
  td:first-child { color: var(--text); font-weight: 500; white-space: nowrap; }
  @media (max-width: 820px) {
    .wrap { grid-template-columns: 1fr; gap: 1.5rem; }
    nav { position: static; }
  }
`;

const renderMarkdown = async (markdown: string): Promise<string> =>
  String(
    await unified()
      .use(remarkParse)
      .use(remarkGfm)
      .use(remarkRehype)
      .use(rehypeSlug)
      .use(rehypeStringify)
      .process(markdown),
  );

export async function writeGuideHtml(
  markdown: string,
  scenes: Scene[],
  cfg: GuideConfig,
): Promise<void> {
  const toc = [
    { href: "#controls-cheat-sheet", label: "Controls cheat-sheet" },
    ...scenes.map((s) => ({ href: `#${s.slug}`, label: s.title })),
    { href: "#glossary", label: "Glossary" },
  ];
  const navHtml = `<nav><div class="label">Contents</div><ol>${toc
    .map((t) => `<li><a href="${esc(t.href)}">${esc(t.label)}</a></li>`)
    .join("")}</ol></nav>`;
  const bodyHtml = await renderMarkdown(markdown);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(cfg.title)}</title>
<!-- Generated by \`${esc(cfg.generateCmd)}\`. ${esc(cfg.editHint)} -->
<style>${STYLE}</style>
</head>
<body>
<div class="wrap">
<header class="brand"><span class="name">${esc(cfg.brandName)}</span><span class="sub">${esc(cfg.brandSub)}</span></header>
${navHtml}
<main>
${bodyHtml}
</main>
</div>
</body>
</html>
`;

  writeFileSync(cfg.htmlPath, html, "utf8");
}
